apply plugin: 'com.android.library'

group = 'expo.modules.faceblur'
version = '1.0.0'

def expoModulesCorePlugin = new File(
  project(':expo-modules-core').projectDir.absolutePath,
  'ExpoModulesCorePlugin.gradle'
)
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()
useDefaultAndroidSdkVersions()

android {
  namespace 'expo.modules.faceblur'

  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }

  sourceSets {
    main.assets.srcDirs += ["${projectDir}/../ios/Resources"]
  }

  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'androidx.media3:media3-common:1.10.1'
  implementation 'androidx.media3:media3-effect:1.10.1'
  implementation 'androidx.media3:media3-transformer:1.10.1'
  implementation 'ai.quickpose:quickpose-mp:0.6'
  implementation 'ai.quickpose:quickpose-core:0.22'
  implementation 'com.google.flogger:flogger:0.9'
  implementation 'com.google.flogger:flogger-system-backend:0.9'
  implementation 'com.google.guava:guava:27.0.1-android'
  implementation 'com.google.protobuf:protobuf-javalite:3.19.1'
  implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.28.0'
}
