const { withGradleProperties, withPodfile } = require('expo/config-plugins');

const QUICKPOSE_PODS = `  # @generated by Luche privacy blur
  pod 'QuickPoseCore', :git => 'https://github.com/quickpose/quickpose-ios-sdk.git', :tag => 'v1.4.0'
  pod 'QuickPoseCamera', :git => 'https://github.com/quickpose/quickpose-ios-sdk.git', :tag => 'v1.4.0'
  pod 'QuickPoseSwiftUI', :git => 'https://github.com/quickpose/quickpose-ios-sdk.git', :tag => 'v1.4.0'
  # @end generated Luche privacy blur
`;

/** QuickPose Android requires API 26; keep the CNG project reproducible. */
module.exports = function withFaceBlurNativeRequirements(config) {
  config = withGradleProperties(config, (next) => {
    next.modResults = next.modResults.filter(
      (item) => item.type !== 'property' || item.key !== 'android.minSdkVersion',
    );
    next.modResults.push({
      type: 'property',
      key: 'android.minSdkVersion',
      value: '26',
    });
    return next;
  });

  // QuickPose's React Native podspec declares these dependencies, but the
  // vendor publishes their podspecs from GitHub rather than CocoaPods trunk.
  return withPodfile(config, (next) => {
    if (next.modResults.contents.includes('@generated by Luche privacy blur')) {
      next.modResults.contents = next.modResults.contents.replace(
        /  # @generated by Luche privacy blur\n[\s\S]*?  # @end generated Luche privacy blur\n/,
        QUICKPOSE_PODS,
      );
      return next;
    }
    const updated = next.modResults.contents.replace(
      /(target\s+['"][^'"]+['"]\s+do\n)/,
      `$1${QUICKPOSE_PODS}`,
    );
    if (updated === next.modResults.contents) {
      throw new Error('Could not add the QuickPose Git pods to the generated iOS Podfile.');
    }
    next.modResults.contents = updated;
    return next;
  });
};
